name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install xz-utils (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install xz-utils
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          plugin: nerves-toolchain
          version: v13.2.0-aarch64-nerves-linux-gnu
          command: aarch64-nerves-linux-gnu-gcc --version
          # workaround for https://github.com/asdf-vm/actions/issues/599
          # head_ref for pull requests, ref_name for branches and tags
          gitref: ${{ github.head_ref || github.ref_name }}
